### ISSUE TITLE
Update the total amount when plus and minus buttons are clicked

### ISSUE THREAD

**Issue by samuel-ma** [samuel-ma/E-Cart#11]
The total amount doesn't update when the quantity of items on the cart is selected

**Comment by samuel-ma** [comment]
The quantity changes when the plus and minus buttons are clicked and that affects the total amount

**Comment by Vishu-uut** [comment]
Want me to fix this issue? I already know your project quite well..

**Comment by samuel-ma** [comment]
You don't need to ask bro, it's open source
If you have a solution....
Create a pull request and let me merge it and see if it works out
The total amount is actually quite frustrating 
The approach I took here was to use buttons instead of an input to update the quantity so it makes this quite difficult

**Comment by Vishu-uut** [comment]
@samuel-ma can you please confirm if my previous PR was of any use to you? I am actually new to open source and you mentioned that in my PR there was no code change?

**Comment by samuel-ma** [comment]
I did confirm, the code is running on VScode right now and the total amount isn't updating
It's going to take alot more lines of code to get it done
You probably need to use the event.target method on the plus and minus buttons to access the location of each iteration
The approach is just confusing that's all
