### ISSUE TITLE
Update the total amount when delete button is clicked

### ISSUE THREAD

**Issue by samuel-ma** [samuel-ma/E-Cart#12]
Deleting an item from the cart affects the total amount as well
Need help find an approach to solving this issue

**Comment by Lz-01** [comment]
can you please assign this issue to me?

**Comment by samuel-ma** [comment]
Go ahead, work on a solution and make a pull request

**Comment by samuel-ma** [comment]
> @Lz-01 
Go ahead, work on a solution and make a pull request

**Comment by F-Hamid** [comment]
Hello!
check your pull request =>
I fixed the issue about deleting the amount and take the opportunity to optimize your JS code.
I'm here for any question or more help!

**Comment by samuel-ma** [comment]
@F-Hamid 
Can't see any pull requests currently on this repo
Please check again so I can confirm your changes

**Comment by F-Hamid** [comment]
![pull req](https://user-images.githubusercontent.com/82233609/200179244-86f027b1-f99c-469d-8168-e66d2a3b33c4.png)
iIcan see the pull request. here's the pic of it. 
check again !

**Comment by samuel-ma** [comment]
@F-Hamid 
Your pull request is 4 commits behind unfortunately
It can no longer be merged with the main branch

![hamid](https://user-images.githubusercontent.com/82509653/200189807-11324b59-d32b-49a3-9869-3ab652af2897.PNG)

**Comment by samuel-ma** [comment]
@F-Hamid 
You spoke about deleting the amount which is not what I was looking for
Also, I've reviewed your changes and there wasn't anything relevant
Thanks for the help though

**Comment by F-Hamid** [comment]
your welcome
