### ISSUE TITLE
Sum of all the items in the cart

### ISSUE THREAD

**Issue by samuel-ma** [samuel-ma/E-Cart#8]

**Comment by Vishu-uut** [comment]
What exactly is the issue? I know Javascript pretty well and I think I can fix it easily. Please provide a description of the issue and assign me this task.

**Comment by samuel-ma** [comment]
> What exactly is the issue? I know Javascript pretty well and I think I can fix it easily. Please provide a description of the issue and assign me this task.

I can't seem to calculate the total amount of all items in the cart once the quantity has been set, it comes out as Not a Number (NaN)
I would really appreciate the help

**Comment by Vishu-uut** [comment]
Hi @samuel-ma your code contain a lot of repetitions which is ofcource not a good practice. Anyways I will fix the issue within 6 -8 hrs, going for classes.

**Comment by Vishu-uut** [comment]
Fixed the issue, hoping it will get merged soon.

**Comment by samuel-ma** [comment]
@Vishu-uut 
The total updates just fine now, thanks
